### ISSUE TITLE
bro is this library support vue3 

### ISSUE THREAD

**Issue by xalteropsx** [manatlan/vbuild#8]
is this support optional api and composition api 

i didnt yet saw those two thing side by side on python

also i wonder why the transcrypt not updating much the community also too low cause of no discord

**Comment by manatlan** [comment]
no, sorry

**Comment by falkoschindler** [comment]
I wasn't aware until just now that vbuild is limited to Vue 2 (with an end-of-life in 5 months).
@manatlan, what do you think, is there any chance vbuild could add Vue 3 support in the future? Or would it basically require a rewrite?

**Comment by manatlan** [comment]
No chance to support vue3 soon... (I don't use vuejs anymore for some years, so not with me)

I can accept PR, but I think it could be more complex ... So a full rewrite is perhaps the best option.
